# Generated by Django 4.2.9 on 2024-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_remove_user_email_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expires', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
