# Generated by Django 5.0.1 on 2024-01-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد تایید')),
                ('expirition_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
