# Generated by Django 5.0.1 on 2024-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_otp_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expirition_date',
            new_name='expiration_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
