# Generated by Django 5.0.1 on 2024-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_expirition_date_otp_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default=' ', max_length=255, verbose_name='توکن'),
            preserve_default=False,
        ),
    ]
